version: "3"
services:
  database:
    container_name: "mariadb"
    image: mariadb:10
    ports:
      - 3310:3306
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: root
      MARIADB_PASSWORD: 8787
      MARIADB_ROOT_PASSWORD: 8787
    restart: always
    healthcheck:
      test: [ "CMD", "nc", "-vz", "localhost", "9092" ]
      interval: 30s
      timeout: 5s
      retries: 4

  reviewservice:
    image: gopang:spring-boot
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 8787
    depends_on:
      - database
    restart: always

